# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .activity_log_actor import ActivityLogActor
    from .activity_log_actor_type_enum import ActivityLogActorTypeEnum
    from .activity_log_details import ActivityLogDetails
    from .activity_log_entry import ActivityLogEntry
    from .activity_log_event_type_enum import ActivityLogEventTypeEnum
    from .activity_log_status_enum import ActivityLogStatusEnum
    from .admin_email import AdminEmail
    from .bad_request_error_body import BadRequestErrorBody
    from .client_id import ClientId
    from .conflict_error_body import ConflictErrorBody
    from .create_members_tenants_response_content import CreateMembersTenantsResponseContent
    from .create_tenants_request_content import CreateTenantsRequestContent
    from .create_tenants_response_content import CreateTenantsResponseContent
    from .created_at import CreatedAt
    from .date_time_iso import DateTimeIso
    from .delete_members_tenants_response_content import DeleteMembersTenantsResponseContent
    from .delete_members_tenants_success_item import DeleteMembersTenantsSuccessItem
    from .environment import Environment
    from .environment_type_enum import EnvironmentTypeEnum
    from .forbidden_error_body import ForbiddenErrorBody
    from .get_members_response_content import GetMembersResponseContent
    from .get_tenants_response_content import GetTenantsResponseContent
    from .internal_server_error_body import InternalServerErrorBody
    from .invite_members_response_content import InviteMembersResponseContent
    from .list_activity_response_content import ListActivityResponseContent
    from .list_environments_response_content import ListEnvironmentsResponseContent
    from .list_members_response_content import ListMembersResponseContent
    from .list_members_tenants_response_content import ListMembersTenantsResponseContent
    from .list_tenants_members_response_content import ListTenantsMembersResponseContent
    from .list_tenants_response_content import ListTenantsResponseContent
    from .management_client import ManagementClient
    from .member_tenant_item import MemberTenantItem
    from .members_tenants_bulk_summary import MembersTenantsBulkSummary
    from .members_tenants_failure_item import MembersTenantsFailureItem
    from .members_tenants_success_item import MembersTenantsSuccessItem
    from .next import Next
    from .not_found_error_body import NotFoundErrorBody
    from .private_cloud_environment import PrivateCloudEnvironment
    from .private_cloud_payload import PrivateCloudPayload
    from .private_cloud_response_content import PrivateCloudResponseContent
    from .public_cloud_payload import PublicCloudPayload
    from .public_cloud_region import PublicCloudRegion
    from .public_cloud_response_content import PublicCloudResponseContent
    from .region import Region
    from .team_member import TeamMember
    from .team_member_role_enum import TeamMemberRoleEnum
    from .tenant_fqdn import TenantFqdn
    from .tenant_id import TenantId
    from .tenant_item import TenantItem
    from .tenant_member import TenantMember
    from .tenant_member_role_enum import TenantMemberRoleEnum
    from .tenant_name import TenantName
    from .tenant_role_assignment import TenantRoleAssignment
    from .too_many_requests_error_body import TooManyRequestsErrorBody
    from .unauthorized_error_body import UnauthorizedErrorBody
    from .update_members_response_content import UpdateMembersResponseContent
    from .update_members_tenants_response_content import UpdateMembersTenantsResponseContent
_dynamic_imports: typing.Dict[str, str] = {
    "ActivityLogActor": ".activity_log_actor",
    "ActivityLogActorTypeEnum": ".activity_log_actor_type_enum",
    "ActivityLogDetails": ".activity_log_details",
    "ActivityLogEntry": ".activity_log_entry",
    "ActivityLogEventTypeEnum": ".activity_log_event_type_enum",
    "ActivityLogStatusEnum": ".activity_log_status_enum",
    "AdminEmail": ".admin_email",
    "BadRequestErrorBody": ".bad_request_error_body",
    "ClientId": ".client_id",
    "ConflictErrorBody": ".conflict_error_body",
    "CreateMembersTenantsResponseContent": ".create_members_tenants_response_content",
    "CreateTenantsRequestContent": ".create_tenants_request_content",
    "CreateTenantsResponseContent": ".create_tenants_response_content",
    "CreatedAt": ".created_at",
    "DateTimeIso": ".date_time_iso",
    "DeleteMembersTenantsResponseContent": ".delete_members_tenants_response_content",
    "DeleteMembersTenantsSuccessItem": ".delete_members_tenants_success_item",
    "Environment": ".environment",
    "EnvironmentTypeEnum": ".environment_type_enum",
    "ForbiddenErrorBody": ".forbidden_error_body",
    "GetMembersResponseContent": ".get_members_response_content",
    "GetTenantsResponseContent": ".get_tenants_response_content",
    "InternalServerErrorBody": ".internal_server_error_body",
    "InviteMembersResponseContent": ".invite_members_response_content",
    "ListActivityResponseContent": ".list_activity_response_content",
    "ListEnvironmentsResponseContent": ".list_environments_response_content",
    "ListMembersResponseContent": ".list_members_response_content",
    "ListMembersTenantsResponseContent": ".list_members_tenants_response_content",
    "ListTenantsMembersResponseContent": ".list_tenants_members_response_content",
    "ListTenantsResponseContent": ".list_tenants_response_content",
    "ManagementClient": ".management_client",
    "MemberTenantItem": ".member_tenant_item",
    "MembersTenantsBulkSummary": ".members_tenants_bulk_summary",
    "MembersTenantsFailureItem": ".members_tenants_failure_item",
    "MembersTenantsSuccessItem": ".members_tenants_success_item",
    "Next": ".next",
    "NotFoundErrorBody": ".not_found_error_body",
    "PrivateCloudEnvironment": ".private_cloud_environment",
    "PrivateCloudPayload": ".private_cloud_payload",
    "PrivateCloudResponseContent": ".private_cloud_response_content",
    "PublicCloudPayload": ".public_cloud_payload",
    "PublicCloudRegion": ".public_cloud_region",
    "PublicCloudResponseContent": ".public_cloud_response_content",
    "Region": ".region",
    "TeamMember": ".team_member",
    "TeamMemberRoleEnum": ".team_member_role_enum",
    "TenantFqdn": ".tenant_fqdn",
    "TenantId": ".tenant_id",
    "TenantItem": ".tenant_item",
    "TenantMember": ".tenant_member",
    "TenantMemberRoleEnum": ".tenant_member_role_enum",
    "TenantName": ".tenant_name",
    "TenantRoleAssignment": ".tenant_role_assignment",
    "TooManyRequestsErrorBody": ".too_many_requests_error_body",
    "UnauthorizedErrorBody": ".unauthorized_error_body",
    "UpdateMembersResponseContent": ".update_members_response_content",
    "UpdateMembersTenantsResponseContent": ".update_members_tenants_response_content",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ActivityLogActor",
    "ActivityLogActorTypeEnum",
    "ActivityLogDetails",
    "ActivityLogEntry",
    "ActivityLogEventTypeEnum",
    "ActivityLogStatusEnum",
    "AdminEmail",
    "BadRequestErrorBody",
    "ClientId",
    "ConflictErrorBody",
    "CreateMembersTenantsResponseContent",
    "CreateTenantsRequestContent",
    "CreateTenantsResponseContent",
    "CreatedAt",
    "DateTimeIso",
    "DeleteMembersTenantsResponseContent",
    "DeleteMembersTenantsSuccessItem",
    "Environment",
    "EnvironmentTypeEnum",
    "ForbiddenErrorBody",
    "GetMembersResponseContent",
    "GetTenantsResponseContent",
    "InternalServerErrorBody",
    "InviteMembersResponseContent",
    "ListActivityResponseContent",
    "ListEnvironmentsResponseContent",
    "ListMembersResponseContent",
    "ListMembersTenantsResponseContent",
    "ListTenantsMembersResponseContent",
    "ListTenantsResponseContent",
    "ManagementClient",
    "MemberTenantItem",
    "MembersTenantsBulkSummary",
    "MembersTenantsFailureItem",
    "MembersTenantsSuccessItem",
    "Next",
    "NotFoundErrorBody",
    "PrivateCloudEnvironment",
    "PrivateCloudPayload",
    "PrivateCloudResponseContent",
    "PublicCloudPayload",
    "PublicCloudRegion",
    "PublicCloudResponseContent",
    "Region",
    "TeamMember",
    "TeamMemberRoleEnum",
    "TenantFqdn",
    "TenantId",
    "TenantItem",
    "TenantMember",
    "TenantMemberRoleEnum",
    "TenantName",
    "TenantRoleAssignment",
    "TooManyRequestsErrorBody",
    "UnauthorizedErrorBody",
    "UpdateMembersResponseContent",
    "UpdateMembersTenantsResponseContent",
]
