# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .activity_log_actor_type_enum import ActivityLogActorTypeEnum


class ActivityLogActor(UniversalBaseModel):
    """
    Actor object; structure may vary as per event type and actor details
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the actor
    """

    type: ActivityLogActorTypeEnum
    name: str = pydantic.Field()
    """
    Name of the actor
    """

    picture: typing.Optional[str] = pydantic.Field(default=None)
    """
    Profile picture URL (for user actors)
    """

    is_member: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="isMember"),
        pydantic.Field(alias="isMember", description="Whether the actor is a team member"),
    ] = None
    """
    Whether the actor is a team member
    """

    team_role: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="teamRole"),
        pydantic.Field(alias="teamRole", description="Team role of the actor"),
    ] = None
    """
    Team role of the actor
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
