# This file was auto-generated by Fern from our API Definition.

import typing

ActivityLogEventTypeEnum = typing.Union[
    typing.Literal[
        "Team Member",
        "Team Invitation",
        "Security Policy",
        "Team Settings",
        "Token Activity",
        "Tenant Activity",
        "Tenant Member",
        "Team Activity",
        "Teams API M2M Activity",
    ],
    typing.Any,
]
