# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .activity_log_actor import ActivityLogActor
from .activity_log_details import ActivityLogDetails
from .activity_log_event_type_enum import ActivityLogEventTypeEnum
from .activity_log_status_enum import ActivityLogStatusEnum


class ActivityLogEntry(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier of the log entry
    """

    type: typing.Optional[ActivityLogEventTypeEnum] = None
    status: ActivityLogStatusEnum
    details: typing.Optional[ActivityLogDetails] = None
    ip: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source IP address
    """

    hostname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Origin hostname (if available)
    """

    user_agent: typing.Optional[str] = pydantic.Field(default=None)
    """
    User agent string (if applicable)
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    Event schema or system version
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the event was created
    """

    current_event: str = pydantic.Field()
    """
    Current event identifier
    """

    actor: ActivityLogActor

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
