# This file was auto-generated by Fern from our API Definition.

import typing

ActivityLogDetails = typing.Dict[str, typing.Any]
"""
Structured event-specific data. This will vary event to event
"""
