# This file was auto-generated by Fern from our API Definition.

AdminEmail = str
"""
The email of the person that will be added as an admin of the tenant. The person must be a member of the team.
"""
