# This file was auto-generated by Fern from our API Definition.

import typing

from .private_cloud_payload import PrivateCloudPayload
from .public_cloud_payload import PublicCloudPayload

CreateTenantsRequestContent = typing.Union[PublicCloudPayload, PrivateCloudPayload]
