# This file was auto-generated by Fern from our API Definition.

import typing

from .private_cloud_response_content import PrivateCloudResponseContent
from .public_cloud_response_content import PublicCloudResponseContent

CreateTenantsResponseContent = typing.Union[PublicCloudResponseContent, PrivateCloudResponseContent]
