# This file was auto-generated by Fern from our API Definition.

import datetime as dt

CreatedAt = dt.datetime
"""
The date and time when the tenant was created, formatted in ISO 8601 standard. This timestamp ensures consistency across time zones and systems
"""
