# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_id import ClientId
from .team_member_role_enum import TeamMemberRoleEnum
from .tenant_id import TenantId
from .tenant_member_role_enum import TenantMemberRoleEnum


class InviteMembersResponseContent(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The unique ID of the newly created team member
    """

    email: str = pydantic.Field()
    """
    The email of the team member
    """

    role: TeamMemberRoleEnum
    tenant_ids: typing.Optional[typing.List[TenantId]] = pydantic.Field(default=None)
    """
    The list of tenants granted to the team member
    """

    tenant_roles: typing.Optional[typing.List[TenantMemberRoleEnum]] = pydantic.Field(default=None)
    """
    The list the roles granted to the team member for each tenant
    """

    client_ids: typing.Optional[typing.List[ClientId]] = pydantic.Field(default=None)
    """
    The list of apps the user has access to under the editor-specific-apps role.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
