# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .member_tenant_item import MemberTenantItem


class ListMembersTenantsResponseContent(UniversalBaseModel):
    environment: str = pydantic.Field()
    """
    The queried environment.
    """

    tenants: typing.List[MemberTenantItem] = pydantic.Field()
    """
    Member tenant access list
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
