# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .activity_log_entry import ActivityLogEntry
from .next import Next


class ListActivityResponseContent(UniversalBaseModel):
    logs: typing.List[ActivityLogEntry] = pydantic.Field()
    """
    List of activity log entries
    """

    next: typing.Optional[Next] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
