# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ManagementClient(UniversalBaseModel):
    """
    The Auth0 Management Client credentials required to authenticate and interact with the newly created tenant. These credentials allow authorized access to manage the tenant's configuration, resources, and API interactions.
    """

    client_name: str = pydantic.Field()
    """
    The name of the Machine to Machine client, which is used for secure, automated interactions with the tenant's APIs and services.
    """

    client_id: str = pydantic.Field()
    """
    The id of the Machine to Machine client, which is used for secure, automated interactions with the tenant's APIs and services.
    """

    client_secret: str = pydantic.Field()
    """
    The client secret the Machine to Machine client, which is used for secure, automated interactions with the tenant's APIs and services.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
