# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_id import ClientId
from .tenant_id import TenantId
from .tenant_member_role_enum import TenantMemberRoleEnum


class MembersTenantsSuccessItem(UniversalBaseModel):
    tenant_id: TenantId
    roles: typing.List[TenantMemberRoleEnum] = pydantic.Field()
    """
    List of roles assigned to the tenant member
    """

    client_ids: typing.Optional[typing.List[ClientId]] = pydantic.Field(default=None)
    """
    Only if nested role is editor-specific-app
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
