# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tenant_id import TenantId


class MembersTenantsFailureItem(UniversalBaseModel):
    tenant_id: TenantId
    status: int = pydantic.Field()
    """
    Status code of failure
    """

    title: str = pydantic.Field()
    """
    A short human-readable summary of the error
    """

    type: str = pydantic.Field()
    """
    A specific error code (e.g., VALIDATION_ERROR, UNAUTHORIZED, TENANT_LIMIT_REACHED)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
