# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tenant_fqdn import TenantFqdn
from .tenant_id import TenantId
from .tenant_role_assignment import TenantRoleAssignment


class MemberTenantItem(UniversalBaseModel):
    tenant_id: TenantId
    domain: TenantFqdn
    roles: typing.List[TenantRoleAssignment] = pydantic.Field()
    """
    An array of roles assigned to the team member within the tenant.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
