# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .admin_email import AdminEmail
from .private_cloud_environment import PrivateCloudEnvironment
from .tenant_name import TenantName


class PrivateCloudPayload(UniversalBaseModel):
    tenant_name: typing.Optional[TenantName] = None
    admin_email: AdminEmail
    environment: PrivateCloudEnvironment

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
