# This file was auto-generated by Fern from our API Definition.

PublicCloudRegion = str
"""
Specifies the Auth0 Public Cloud locality where the tenant will be created.<br> Available localities include United States (us), Europe (eu), Australia (au), Japan (jp), Canada (ca) and United Kingdom (uk).
"""
