# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .created_at import CreatedAt
from .environment import Environment
from .environment_type_enum import EnvironmentTypeEnum
from .management_client import ManagementClient
from .region import Region
from .tenant_fqdn import TenantFqdn
from .tenant_name import TenantName


class PublicCloudResponseContent(UniversalBaseModel):
    tenant_id: str = pydantic.Field()
    """
    The unique identifier of the created tenant (UUID). This identifier is required for performing operations such as deleting the tenant. UUIDs ensure global uniqueness and are essential for managing tenant resources programmatically
    """

    tenant_name: TenantName
    domain: TenantFqdn
    environment_tag: typing.Optional[EnvironmentTypeEnum] = None
    locality: Region
    environment: Environment
    created_at: CreatedAt
    management_client: ManagementClient

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
