# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .team_member_role_enum import TeamMemberRoleEnum


class TeamMember(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    The unique ID of the team member.
    """

    name: str = pydantic.Field()
    """
    The full name of the team member.
    """

    given_name: str = pydantic.Field()
    """
    The first name of the team member. Returns empty string if not set.
    """

    family_name: str = pydantic.Field()
    """
    The last name of the team member. Returns empty string if not set.
    """

    nickname: str = pydantic.Field()
    """
    The nickname of the team member. Returns empty string if not set.
    """

    email: str = pydantic.Field()
    """
    The email of the team member.
    """

    role: TeamMemberRoleEnum

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
