# This file was auto-generated by Fern from our API Definition.

import typing

TeamMemberRoleEnum = typing.Union[
    typing.Literal["teams_owner", "teams_contributor", "teams_report_viewer", "teams_tenant_manager"], typing.Any
]
