# This file was auto-generated by Fern from our API Definition.

TenantFqdn = str
"""
The fully qualified domain name of the tenant, which uniquely identifies its domain within the system. The domain is used to define the audience when interacting with the Management API, enabling programmatic management of the tenant’s configuration and resources.
"""
