# This file was auto-generated by Fern from our API Definition.

import typing

TenantMemberRoleEnum = typing.Union[
    typing.Literal[
        "owner",
        "editor-connections",
        "editor-users",
        "editor-specific-apps",
        "editor-organizations",
        "viewer-config",
        "viewer-users",
        "support-access",
        "elevated-support-access",
        "editor-kms",
    ],
    typing.Any,
]
