# This file was auto-generated by Fern from our API Definition.

TenantName = str
"""
The tenant name uniquely identifies a tenant programmatically and within various dashboards, such as Auth0 Dashboard. It can only contain alphanumeric characters, lowercase letters and "-". However, it can't start nor end with "-". If not specified, a tenant name will be auto-generated.
"""
