# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .created_at import CreatedAt
from .environment import Environment
from .environment_type_enum import EnvironmentTypeEnum
from .region import Region
from .tenant_fqdn import TenantFqdn
from .tenant_id import TenantId
from .tenant_name import TenantName


class TenantItem(UniversalBaseModel):
    """
    A tenant associated with your team
    """

    tenant_id: TenantId
    tenant_name: TenantName
    environment: Environment
    environment_tag: typing.Optional[EnvironmentTypeEnum] = None
    domain: TenantFqdn
    locality: Region
    created_at: CreatedAt

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
