# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .client_id import ClientId
from .tenant_member_role_enum import TenantMemberRoleEnum


class TenantRoleAssignment(UniversalBaseModel):
    role: TenantMemberRoleEnum = pydantic.Field()
    """
    The role assigned to the member.
    """

    client_ids: typing.Optional[typing.List[ClientId]] = pydantic.Field(default=None)
    """
    The list of apps the user has access to for the 'editor-specific-apps' role. This property is only present for this role.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
