# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .team_member_role_enum import TeamMemberRoleEnum


class UpdateMembersResponseContent(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique ID of the team member.
    """

    email: str = pydantic.Field()
    """
    Email of the team member
    """

    role: TeamMemberRoleEnum = pydantic.Field()
    """
    The team-level role of the team member.
    """

    name: str = pydantic.Field()
    """
    Full name of the team member
    """

    given_name: str = pydantic.Field()
    """
    First name of the team member. Returns empty string if not set.
    """

    family_name: str = pydantic.Field()
    """
    Last name of the team member. Returns empty string if not set
    """

    nickname: str = pydantic.Field()
    """
    Nickname of the team member. Returns empty string if not set.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
