# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .members_tenants_bulk_summary import MembersTenantsBulkSummary
from .members_tenants_failure_item import MembersTenantsFailureItem
from .members_tenants_success_item import MembersTenantsSuccessItem


class UpdateMembersTenantsResponseContent(UniversalBaseModel):
    status_code: int = pydantic.Field()
    """
    Status code for partial response
    """

    message: str = pydantic.Field()
    """
    Describing the partial error scenario
    """

    summary: MembersTenantsBulkSummary
    success: typing.List[MembersTenantsSuccessItem] = pydantic.Field()
    """
    List of successful instances
    """

    failure: typing.List[MembersTenantsFailureItem] = pydantic.Field()
    """
    List of failed instances
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
