# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.list_tenants_members_response_content import ListTenantsMembersResponseContent
from ...types.tenant_id import TenantId
from ...types.tenant_member import TenantMember
from .raw_client import AsyncRawMembersClient, RawMembersClient


class MembersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMembersClient
        """
        return self._raw_client

    def list(
        self,
        tenant_id: TenantId,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[TenantMember, ListTenantsMembersResponseContent]:
        """
        This endpoint retrieves a paginated list of all members for a specific tenant.

        Parameters
        ----------
        tenant_id : TenantId
            The unique ID of the tenant.

        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[TenantMember, ListTenantsMembersResponseContent]
            A paginated list of tenant members

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        response = client.tenants.members.list(
            tenant_id="tenantId",
            take=1,
            from_="from",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(tenant_id, take=take, from_=from_, request_options=request_options)


class AsyncMembersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMembersClient
        """
        return self._raw_client

    async def list(
        self,
        tenant_id: TenantId,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[TenantMember, ListTenantsMembersResponseContent]:
        """
        This endpoint retrieves a paginated list of all members for a specific tenant.

        Parameters
        ----------
        tenant_id : TenantId
            The unique ID of the tenant.

        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[TenantMember, ListTenantsMembersResponseContent]
            A paginated list of tenant members

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.tenants.members.list(
                tenant_id="tenantId",
                take=1,
                from_="from",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(tenant_id, take=take, from_=from_, request_options=request_options)
