# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.create_tenants_request_content import CreateTenantsRequestContent
from ..types.create_tenants_response_content import CreateTenantsResponseContent
from ..types.environment_type_enum import EnvironmentTypeEnum
from ..types.get_tenants_response_content import GetTenantsResponseContent
from ..types.list_tenants_response_content import ListTenantsResponseContent
from ..types.tenant_id import TenantId
from ..types.tenant_item import TenantItem
from .raw_client import AsyncRawTenantsClient, RawTenantsClient

if typing.TYPE_CHECKING:
    from .members.client import AsyncMembersClient, MembersClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TenantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTenantsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._members: typing.Optional[MembersClient] = None

    @property
    def with_raw_response(self) -> RawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTenantsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        sort: typing.Optional[str] = "created_at:-1",
        environment: typing.Optional[str] = None,
        environment_tag: typing.Optional[EnvironmentTypeEnum] = None,
        locality: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[TenantItem, ListTenantsResponseContent]:
        """
        This endpoint retrieves a paginated list of tenants for a specified team. It supports cursor-based pagination to ensure efficient data retrieval across large datasets. If the private cloud support beta is enabled for the team, the response includes both public and private tenants; otherwise, only public tenants are returned. To navigate results, the next cursor from the response should be used to fetch subsequent pages.

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        sort : typing.Optional[str]
            Sort order for results using MongoDB-style syntax. Defaults to 'created_at:-1' (newest first, descending). Use 'created_at:1' for oldest first (ascending). Format: field:direction where direction is 1 (ascending) or -1 (descending).

        environment : typing.Optional[str]
            Filter tenants by environment. For public cloud tenants, use the short name (e.g., 'US-3', 'EU-1'). For private cloud tenants, use the space name (e.g., 'acme-dev').

        environment_tag : typing.Optional[EnvironmentTypeEnum]
            Filter tenants by environment tag

        locality : typing.Optional[str]
            Filter tenants by locality. For public cloud tenants, matches locality (e.g., 'us', 'eu'). For private cloud tenants, matches the space's primary locality (e.g., 'virginia', 'frankfurt').

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[TenantItem, ListTenantsResponseContent]
            A paginated list of tenants, including tenant details such as ID, name, domain, locality, environment, and creation date. The response also includes a 'next' field for checkpoint-based pagination

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        response = client.tenants.list(
            take=1,
            from_="from",
            sort="sort",
            environment="US-3",
            environment_tag="development",
            locality="us",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            take=take,
            from_=from_,
            sort=sort,
            environment=environment,
            environment_tag=environment_tag,
            locality=locality,
            request_options=request_options,
        )

    def create(
        self, *, request: CreateTenantsRequestContent, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateTenantsResponseContent:
        """
        This endpoint creates a new tenant under your team. Upon successful creation, the response includes the tenant's details and management client credentials. The tenant type (public or private) is determined by the attributes in the request payload. Refer to the payload schema for required attributes.

        Parameters
        ----------
        request : CreateTenantsRequestContent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTenantsResponseContent
            Tenant Created

        Examples
        --------
        from auth0 import PublicCloudPayload, Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.tenants.create(
            request=PublicCloudPayload(
                admin_email="admin_email",
                locality="us",
            ),
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def get(
        self, tenant_id: TenantId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetTenantsResponseContent:
        """
        This endpoint retrieves all metadata for a specific tenant, including the tenant's unique ID, name, domain, environment, locality, environment type, and creation date. It is useful for obtaining comprehensive information about a tenant for display in dashboards, auditing, or automated management tasks. The response includes all relevant fields required to identify and manage the tenant programmatically

        Parameters
        ----------
        tenant_id : TenantId
            The unique ID of the tenant to retrieve (UUID format)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTenantsResponseContent
            Tenant details retrieved successfully, including tenant ID, name, domain, environment, locality, environment type, and creation date.

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.tenants.get(
            tenant_id="tenantId",
        )
        """
        _response = self._raw_client.get(tenant_id, request_options=request_options)
        return _response.data

    def delete(self, tenant_id: TenantId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a tenant from the current team

        Parameters
        ----------
        tenant_id : TenantId
            The id of the tenant to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.tenants.delete(
            tenant_id="tenantId",
        )
        """
        _response = self._raw_client.delete(tenant_id, request_options=request_options)
        return _response.data

    @property
    def members(self):
        if self._members is None:
            from .members.client import MembersClient  # noqa: E402

            self._members = MembersClient(client_wrapper=self._client_wrapper)
        return self._members


class AsyncTenantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTenantsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._members: typing.Optional[AsyncMembersClient] = None

    @property
    def with_raw_response(self) -> AsyncRawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTenantsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        sort: typing.Optional[str] = "created_at:-1",
        environment: typing.Optional[str] = None,
        environment_tag: typing.Optional[EnvironmentTypeEnum] = None,
        locality: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[TenantItem, ListTenantsResponseContent]:
        """
        This endpoint retrieves a paginated list of tenants for a specified team. It supports cursor-based pagination to ensure efficient data retrieval across large datasets. If the private cloud support beta is enabled for the team, the response includes both public and private tenants; otherwise, only public tenants are returned. To navigate results, the next cursor from the response should be used to fetch subsequent pages.

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        sort : typing.Optional[str]
            Sort order for results using MongoDB-style syntax. Defaults to 'created_at:-1' (newest first, descending). Use 'created_at:1' for oldest first (ascending). Format: field:direction where direction is 1 (ascending) or -1 (descending).

        environment : typing.Optional[str]
            Filter tenants by environment. For public cloud tenants, use the short name (e.g., 'US-3', 'EU-1'). For private cloud tenants, use the space name (e.g., 'acme-dev').

        environment_tag : typing.Optional[EnvironmentTypeEnum]
            Filter tenants by environment tag

        locality : typing.Optional[str]
            Filter tenants by locality. For public cloud tenants, matches locality (e.g., 'us', 'eu'). For private cloud tenants, matches the space's primary locality (e.g., 'virginia', 'frankfurt').

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[TenantItem, ListTenantsResponseContent]
            A paginated list of tenants, including tenant details such as ID, name, domain, locality, environment, and creation date. The response also includes a 'next' field for checkpoint-based pagination

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.tenants.list(
                take=1,
                from_="from",
                sort="sort",
                environment="US-3",
                environment_tag="development",
                locality="us",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            take=take,
            from_=from_,
            sort=sort,
            environment=environment,
            environment_tag=environment_tag,
            locality=locality,
            request_options=request_options,
        )

    async def create(
        self, *, request: CreateTenantsRequestContent, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateTenantsResponseContent:
        """
        This endpoint creates a new tenant under your team. Upon successful creation, the response includes the tenant's details and management client credentials. The tenant type (public or private) is determined by the attributes in the request payload. Refer to the payload schema for required attributes.

        Parameters
        ----------
        request : CreateTenantsRequestContent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTenantsResponseContent
            Tenant Created

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams, PublicCloudPayload

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tenants.create(
                request=PublicCloudPayload(
                    admin_email="admin_email",
                    locality="us",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def get(
        self, tenant_id: TenantId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetTenantsResponseContent:
        """
        This endpoint retrieves all metadata for a specific tenant, including the tenant's unique ID, name, domain, environment, locality, environment type, and creation date. It is useful for obtaining comprehensive information about a tenant for display in dashboards, auditing, or automated management tasks. The response includes all relevant fields required to identify and manage the tenant programmatically

        Parameters
        ----------
        tenant_id : TenantId
            The unique ID of the tenant to retrieve (UUID format)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTenantsResponseContent
            Tenant details retrieved successfully, including tenant ID, name, domain, environment, locality, environment type, and creation date.

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tenants.get(
                tenant_id="tenantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(tenant_id, request_options=request_options)
        return _response.data

    async def delete(self, tenant_id: TenantId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a tenant from the current team

        Parameters
        ----------
        tenant_id : TenantId
            The id of the tenant to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tenants.delete(
                tenant_id="tenantId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(tenant_id, request_options=request_options)
        return _response.data

    @property
    def members(self):
        if self._members is None:
            from .members.client import AsyncMembersClient  # noqa: E402

            self._members = AsyncMembersClient(client_wrapper=self._client_wrapper)
        return self._members
