# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.activity_log_entry import ActivityLogEntry
from ..types.activity_log_event_type_enum import ActivityLogEventTypeEnum
from ..types.activity_log_status_enum import ActivityLogStatusEnum
from ..types.date_time_iso import DateTimeIso
from ..types.list_activity_response_content import ListActivityResponseContent
from .raw_client import AsyncRawActivityClient, RawActivityClient


class ActivityClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawActivityClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawActivityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawActivityClient
        """
        return self._raw_client

    def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        since: typing.Optional[DateTimeIso] = None,
        until: typing.Optional[DateTimeIso] = None,
        type: typing.Optional[ActivityLogEventTypeEnum] = None,
        status: typing.Optional[ActivityLogStatusEnum] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ActivityLogEntry, ListActivityResponseContent]:
        """
        This endpoint returns a paginated list of activity log entries for the team.

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        since : typing.Optional[DateTimeIso]
            Return logs created at or after this ISO 8601 date format

        until : typing.Optional[DateTimeIso]
            Return logs created before this ISO 8601 timestamp

        type : typing.Optional[ActivityLogEventTypeEnum]
            Exact match: filter by event type

        status : typing.Optional[ActivityLogStatusEnum]
            Exact match: filter by status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ActivityLogEntry, ListActivityResponseContent]
            A paginated list of audit activity

        Examples
        --------
        import datetime

        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        response = client.activity.list(
            take=1,
            from_="from",
            since=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            until=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            type="Team Member",
            status="Success",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            take=take, from_=from_, since=since, until=until, type=type, status=status, request_options=request_options
        )


class AsyncActivityClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawActivityClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawActivityClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawActivityClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        since: typing.Optional[DateTimeIso] = None,
        until: typing.Optional[DateTimeIso] = None,
        type: typing.Optional[ActivityLogEventTypeEnum] = None,
        status: typing.Optional[ActivityLogStatusEnum] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ActivityLogEntry, ListActivityResponseContent]:
        """
        This endpoint returns a paginated list of activity log entries for the team.

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        since : typing.Optional[DateTimeIso]
            Return logs created at or after this ISO 8601 date format

        until : typing.Optional[DateTimeIso]
            Return logs created before this ISO 8601 timestamp

        type : typing.Optional[ActivityLogEventTypeEnum]
            Exact match: filter by event type

        status : typing.Optional[ActivityLogStatusEnum]
            Exact match: filter by status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ActivityLogEntry, ListActivityResponseContent]
            A paginated list of audit activity

        Examples
        --------
        import asyncio
        import datetime

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.activity.list(
                take=1,
                from_="from",
                since=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                until=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                type="Team Member",
                status="Success",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            take=take, from_=from_, since=since, until=until, type=type, status=status, request_options=request_options
        )
