# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.pagination import AsyncPager, SyncPager
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.too_many_requests_error import TooManyRequestsError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.activity_log_entry import ActivityLogEntry
from ..types.activity_log_event_type_enum import ActivityLogEventTypeEnum
from ..types.activity_log_status_enum import ActivityLogStatusEnum
from ..types.date_time_iso import DateTimeIso
from ..types.list_activity_response_content import ListActivityResponseContent
from pydantic import ValidationError


class RawActivityClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        since: typing.Optional[DateTimeIso] = None,
        until: typing.Optional[DateTimeIso] = None,
        type: typing.Optional[ActivityLogEventTypeEnum] = None,
        status: typing.Optional[ActivityLogStatusEnum] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[ActivityLogEntry, ListActivityResponseContent]:
        """
        This endpoint returns a paginated list of activity log entries for the team.

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        since : typing.Optional[DateTimeIso]
            Return logs created at or after this ISO 8601 date format

        until : typing.Optional[DateTimeIso]
            Return logs created before this ISO 8601 timestamp

        type : typing.Optional[ActivityLogEventTypeEnum]
            Exact match: filter by event type

        status : typing.Optional[ActivityLogStatusEnum]
            Exact match: filter by status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[ActivityLogEntry, ListActivityResponseContent]
            A paginated list of audit activity
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/activity/logs",
            method="GET",
            params={
                "take": take,
                "from": from_,
                "since": serialize_datetime(since) if since is not None else None,
                "until": serialize_datetime(until) if until is not None else None,
                "type": type,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListActivityResponseContent,
                    parse_obj_as(
                        type_=ListActivityResponseContent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.logs
                _parsed_next = _parsed_response.next
                _has_next = _parsed_next is not None and _parsed_next != ""
                _get_next = lambda: self.list(
                    take=take,
                    from_=_parsed_next,
                    since=since,
                    until=until,
                    type=type,
                    status=status,
                    request_options=request_options,
                )
                return SyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawActivityClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        since: typing.Optional[DateTimeIso] = None,
        until: typing.Optional[DateTimeIso] = None,
        type: typing.Optional[ActivityLogEventTypeEnum] = None,
        status: typing.Optional[ActivityLogStatusEnum] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[ActivityLogEntry, ListActivityResponseContent]:
        """
        This endpoint returns a paginated list of activity log entries for the team.

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        since : typing.Optional[DateTimeIso]
            Return logs created at or after this ISO 8601 date format

        until : typing.Optional[DateTimeIso]
            Return logs created before this ISO 8601 timestamp

        type : typing.Optional[ActivityLogEventTypeEnum]
            Exact match: filter by event type

        status : typing.Optional[ActivityLogStatusEnum]
            Exact match: filter by status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[ActivityLogEntry, ListActivityResponseContent]
            A paginated list of audit activity
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/activity/logs",
            method="GET",
            params={
                "take": take,
                "from": from_,
                "since": serialize_datetime(since) if since is not None else None,
                "until": serialize_datetime(until) if until is not None else None,
                "type": type,
                "status": status,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _parsed_response = typing.cast(
                    ListActivityResponseContent,
                    parse_obj_as(
                        type_=ListActivityResponseContent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                _items = _parsed_response.logs
                _parsed_next = _parsed_response.next
                _has_next = _parsed_next is not None and _parsed_next != ""

                async def _get_next():
                    return await self.list(
                        take=take,
                        from_=_parsed_next,
                        since=since,
                        until=until,
                        type=type,
                        status=status,
                        request_options=request_options,
                    )

                return AsyncPager(has_next=_has_next, items=_items, get_next=_get_next, response=_parsed_response)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 429:
                raise TooManyRequestsError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
