# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.client_id import ClientId
from ...types.create_members_tenants_response_content import CreateMembersTenantsResponseContent
from ...types.delete_members_tenants_response_content import DeleteMembersTenantsResponseContent
from ...types.list_members_tenants_response_content import ListMembersTenantsResponseContent
from ...types.tenant_id import TenantId
from ...types.tenant_member_role_enum import TenantMemberRoleEnum
from ...types.update_members_tenants_response_content import UpdateMembersTenantsResponseContent
from .raw_client import AsyncRawTenantsClient, RawTenantsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TenantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTenantsClient
        """
        return self._raw_client

    def create(
        self,
        id: str,
        *,
        tenants: typing.Sequence[TenantId],
        roles: typing.Sequence[TenantMemberRoleEnum],
        client_ids: typing.Optional[typing.Sequence[ClientId]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[CreateMembersTenantsResponseContent]:
        """
        This endpoint can be used to add new tenants access

        Parameters
        ----------
        id : str
            The unique ID of the team member to update

        tenants : typing.Sequence[TenantId]
            A list of tenant ids

        roles : typing.Sequence[TenantMemberRoleEnum]
            List of roles to be assigned to the tenant member

        client_ids : typing.Optional[typing.Sequence[ClientId]]
            List of applications. Only if nested role is editor-specific-app

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[CreateMembersTenantsResponseContent]
            Operation completed with errors

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.tenants.create(
            id="id",
            tenants=[
                "538c9e21-e3d5-4ad6-b3d0-352c62369fb0",
                "b1c9e21e-1234-4ad6-b3d0-352c6236abcd",
            ],
            roles=["owner", "editor-specific-apps"],
            client_ids=["client_123", "client_456"],
        )
        """
        _response = self._raw_client.create(
            id, tenants=tenants, roles=roles, client_ids=client_ids, request_options=request_options
        )
        return _response.data

    def remove(
        self, id: str, *, tenants: typing.Sequence[TenantId], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[DeleteMembersTenantsResponseContent]:
        """
        This endpoint can be used to remove tenant access

        Parameters
        ----------
        id : str
            The unique ID of the team member.

        tenants : typing.Sequence[TenantId]
            Specifies list of tenant IDs to be removed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[DeleteMembersTenantsResponseContent]
            Operation completed with errors

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.tenants.remove(
            id="id",
            tenants=["tenants"],
        )
        """
        _response = self._raw_client.remove(id, tenants=tenants, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        tenants: typing.Sequence[TenantId],
        roles: typing.Sequence[TenantMemberRoleEnum],
        client_ids: typing.Optional[typing.Sequence[ClientId]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[UpdateMembersTenantsResponseContent]:
        """
        This endpoint can be used to update existing tenant roles.

        Parameters
        ----------
        id : str
            The unique ID of the team member to update

        tenants : typing.Sequence[TenantId]
            A list of tenant ids

        roles : typing.Sequence[TenantMemberRoleEnum]
            List of roles to be assigned to the tenant member

        client_ids : typing.Optional[typing.Sequence[ClientId]]
            List of applications. Only if nested role is editor-specific-app

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[UpdateMembersTenantsResponseContent]
            Operation completed with errors

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.tenants.update(
            id="id",
            tenants=["538c9e21-e3d5-4ad6-b3d0-352c62369fb0"],
            roles=["owner", "editor-specific-apps"],
            client_ids=["client_123", "client_456"],
        )
        """
        _response = self._raw_client.update(
            id, tenants=tenants, roles=roles, client_ids=client_ids, request_options=request_options
        )
        return _response.data

    def list(
        self, id: str, environment: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMembersTenantsResponseContent:
        """
        This endpoint retrieves a list of all tenants within a specific environment that the team member has access to. Environment identifiers required for this request can be obtained using the /api/environments endpoint, which provides details for all environments where tenants associated with your team exists.

        Parameters
        ----------
        id : str
            Unique ID of the team member.

        environment : str
            The cloud environment identifier (e.g. 'US-3', 'EU-1', 'acme-dev').

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMembersTenantsResponseContent
            Member tenant access list

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.tenants.list(
            id="id",
            environment="environment",
        )
        """
        _response = self._raw_client.list(id, environment, request_options=request_options)
        return _response.data


class AsyncTenantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTenantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTenantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTenantsClient
        """
        return self._raw_client

    async def create(
        self,
        id: str,
        *,
        tenants: typing.Sequence[TenantId],
        roles: typing.Sequence[TenantMemberRoleEnum],
        client_ids: typing.Optional[typing.Sequence[ClientId]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[CreateMembersTenantsResponseContent]:
        """
        This endpoint can be used to add new tenants access

        Parameters
        ----------
        id : str
            The unique ID of the team member to update

        tenants : typing.Sequence[TenantId]
            A list of tenant ids

        roles : typing.Sequence[TenantMemberRoleEnum]
            List of roles to be assigned to the tenant member

        client_ids : typing.Optional[typing.Sequence[ClientId]]
            List of applications. Only if nested role is editor-specific-app

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[CreateMembersTenantsResponseContent]
            Operation completed with errors

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.tenants.create(
                id="id",
                tenants=[
                    "538c9e21-e3d5-4ad6-b3d0-352c62369fb0",
                    "b1c9e21e-1234-4ad6-b3d0-352c6236abcd",
                ],
                roles=["owner", "editor-specific-apps"],
                client_ids=["client_123", "client_456"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            id, tenants=tenants, roles=roles, client_ids=client_ids, request_options=request_options
        )
        return _response.data

    async def remove(
        self, id: str, *, tenants: typing.Sequence[TenantId], request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[DeleteMembersTenantsResponseContent]:
        """
        This endpoint can be used to remove tenant access

        Parameters
        ----------
        id : str
            The unique ID of the team member.

        tenants : typing.Sequence[TenantId]
            Specifies list of tenant IDs to be removed

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[DeleteMembersTenantsResponseContent]
            Operation completed with errors

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.tenants.remove(
                id="id",
                tenants=["tenants"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove(id, tenants=tenants, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        tenants: typing.Sequence[TenantId],
        roles: typing.Sequence[TenantMemberRoleEnum],
        client_ids: typing.Optional[typing.Sequence[ClientId]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[UpdateMembersTenantsResponseContent]:
        """
        This endpoint can be used to update existing tenant roles.

        Parameters
        ----------
        id : str
            The unique ID of the team member to update

        tenants : typing.Sequence[TenantId]
            A list of tenant ids

        roles : typing.Sequence[TenantMemberRoleEnum]
            List of roles to be assigned to the tenant member

        client_ids : typing.Optional[typing.Sequence[ClientId]]
            List of applications. Only if nested role is editor-specific-app

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[UpdateMembersTenantsResponseContent]
            Operation completed with errors

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.tenants.update(
                id="id",
                tenants=["538c9e21-e3d5-4ad6-b3d0-352c62369fb0"],
                roles=["owner", "editor-specific-apps"],
                client_ids=["client_123", "client_456"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id, tenants=tenants, roles=roles, client_ids=client_ids, request_options=request_options
        )
        return _response.data

    async def list(
        self, id: str, environment: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMembersTenantsResponseContent:
        """
        This endpoint retrieves a list of all tenants within a specific environment that the team member has access to. Environment identifiers required for this request can be obtained using the /api/environments endpoint, which provides details for all environments where tenants associated with your team exists.

        Parameters
        ----------
        id : str
            Unique ID of the team member.

        environment : str
            The cloud environment identifier (e.g. 'US-3', 'EU-1', 'acme-dev').

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMembersTenantsResponseContent
            Member tenant access list

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.tenants.list(
                id="id",
                environment="environment",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(id, environment, request_options=request_options)
        return _response.data
