# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.pagination import AsyncPager, SyncPager
from ..core.request_options import RequestOptions
from ..types.client_id import ClientId
from ..types.get_members_response_content import GetMembersResponseContent
from ..types.invite_members_response_content import InviteMembersResponseContent
from ..types.list_members_response_content import ListMembersResponseContent
from ..types.team_member import TeamMember
from ..types.team_member_role_enum import TeamMemberRoleEnum
from ..types.tenant_id import TenantId
from ..types.tenant_member_role_enum import TenantMemberRoleEnum
from ..types.update_members_response_content import UpdateMembersResponseContent
from .raw_client import AsyncRawMembersClient, RawMembersClient

if typing.TYPE_CHECKING:
    from .tenants.client import AsyncTenantsClient, TenantsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MembersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMembersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._tenants: typing.Optional[TenantsClient] = None

    @property
    def with_raw_response(self) -> RawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMembersClient
        """
        return self._raw_client

    def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[TeamMember, ListMembersResponseContent]:
        """
        This endpoint retrieves a paginated list of all members under the current team. It supports checkpoint-based pagination for efficient retrieval of large datasets

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[TeamMember, ListMembersResponseContent]
            A paginated list of team members

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        response = client.members.list(
            take=1,
            from_="from",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(take=take, from_=from_, request_options=request_options)

    def invite(
        self,
        *,
        email: str,
        role: TeamMemberRoleEnum,
        tenant_ids: typing.Optional[typing.Sequence[TenantId]] = OMIT,
        tenant_roles: typing.Optional[typing.Sequence[TenantMemberRoleEnum]] = OMIT,
        client_ids: typing.Optional[typing.Sequence[ClientId]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InviteMembersResponseContent:
        """
        This endpoint invites a new member to the team and optionally grants them access to one or more tenants with specified roles

        Parameters
        ----------
        email : str
            The email of the team member

        role : TeamMemberRoleEnum

        tenant_ids : typing.Optional[typing.Sequence[TenantId]]
            Specifies an optional list of tenant IDs and their corresponding role assignments.

        tenant_roles : typing.Optional[typing.Sequence[TenantMemberRoleEnum]]
            The list of roles for each tenant.

        client_ids : typing.Optional[typing.Sequence[ClientId]]
            The list of apps the user has access to for the 'editor-specific-apps' role. This property is only present for this role.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InviteMembersResponseContent
            Team member invited

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.invite(
            email="jane.smith@company.com",
            role="teams_contributor",
            tenant_ids=[
                "538c9e21-e3d5-4ad6-b3d0-352c62369fb0",
                "b1c9e21e-1234-4ad6-b3d0-352c6236abcd",
            ],
            tenant_roles=["owner", "editor-users"],
            client_ids=["client_123", "client_456"],
        )
        """
        _response = self._raw_client.invite(
            email=email,
            role=role,
            tenant_ids=tenant_ids,
            tenant_roles=tenant_roles,
            client_ids=client_ids,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetMembersResponseContent:
        """
        Returns the team member's identity and team-level role. Tenant access is retrieved via /api/members/{id}/tenants/{environment}.

        Parameters
        ----------
        id : str
            The unique ID of the team member to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMembersResponseContent
            Team member details retrieved successfully

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This endpoint deletes a team member from the team.

        Parameters
        ----------
        id : str
            The unique ID of the team member to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self, id: str, *, role: TeamMemberRoleEnum, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateMembersResponseContent:
        """
        This endpoint can be used to change the team-level role for the team member

        Parameters
        ----------
        id : str
            The unique ID of the team member to update

        role : TeamMemberRoleEnum
            The new role to assign to the team member.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateMembersResponseContent
            Team member updated successfully

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.members.update(
            id="id",
            role="teams_owner",
        )
        """
        _response = self._raw_client.update(id, role=role, request_options=request_options)
        return _response.data

    @property
    def tenants(self):
        if self._tenants is None:
            from .tenants.client import TenantsClient  # noqa: E402

            self._tenants = TenantsClient(client_wrapper=self._client_wrapper)
        return self._tenants


class AsyncMembersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMembersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._tenants: typing.Optional[AsyncTenantsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMembersClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        take: typing.Optional[int] = 50,
        from_: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[TeamMember, ListMembersResponseContent]:
        """
        This endpoint retrieves a paginated list of all members under the current team. It supports checkpoint-based pagination for efficient retrieval of large datasets

        Parameters
        ----------
        take : typing.Optional[int]
            Maximum number of items to return per page. Defaults to 50. Maximum 50

        from_ : typing.Optional[str]
            Checkpoint cursor for pagination; use the 'next' value from a previous response to fetch the next page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[TeamMember, ListMembersResponseContent]
            A paginated list of team members

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = await client.members.list(
                take=1,
                from_="from",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(take=take, from_=from_, request_options=request_options)

    async def invite(
        self,
        *,
        email: str,
        role: TeamMemberRoleEnum,
        tenant_ids: typing.Optional[typing.Sequence[TenantId]] = OMIT,
        tenant_roles: typing.Optional[typing.Sequence[TenantMemberRoleEnum]] = OMIT,
        client_ids: typing.Optional[typing.Sequence[ClientId]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InviteMembersResponseContent:
        """
        This endpoint invites a new member to the team and optionally grants them access to one or more tenants with specified roles

        Parameters
        ----------
        email : str
            The email of the team member

        role : TeamMemberRoleEnum

        tenant_ids : typing.Optional[typing.Sequence[TenantId]]
            Specifies an optional list of tenant IDs and their corresponding role assignments.

        tenant_roles : typing.Optional[typing.Sequence[TenantMemberRoleEnum]]
            The list of roles for each tenant.

        client_ids : typing.Optional[typing.Sequence[ClientId]]
            The list of apps the user has access to for the 'editor-specific-apps' role. This property is only present for this role.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InviteMembersResponseContent
            Team member invited

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.invite(
                email="jane.smith@company.com",
                role="teams_contributor",
                tenant_ids=[
                    "538c9e21-e3d5-4ad6-b3d0-352c62369fb0",
                    "b1c9e21e-1234-4ad6-b3d0-352c6236abcd",
                ],
                tenant_roles=["owner", "editor-users"],
                client_ids=["client_123", "client_456"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invite(
            email=email,
            role=role,
            tenant_ids=tenant_ids,
            tenant_roles=tenant_roles,
            client_ids=client_ids,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMembersResponseContent:
        """
        Returns the team member's identity and team-level role. Tenant access is retrieved via /api/members/{id}/tenants/{environment}.

        Parameters
        ----------
        id : str
            The unique ID of the team member to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMembersResponseContent
            Team member details retrieved successfully

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        This endpoint deletes a team member from the team.

        Parameters
        ----------
        id : str
            The unique ID of the team member to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self, id: str, *, role: TeamMemberRoleEnum, request_options: typing.Optional[RequestOptions] = None
    ) -> UpdateMembersResponseContent:
        """
        This endpoint can be used to change the team-level role for the team member

        Parameters
        ----------
        id : str
            The unique ID of the team member to update

        role : TeamMemberRoleEnum
            The new role to assign to the team member.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateMembersResponseContent
            Team member updated successfully

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.update(
                id="id",
                role="teams_owner",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, role=role, request_options=request_options)
        return _response.data

    @property
    def tenants(self):
        if self._tenants is None:
            from .tenants.client import AsyncTenantsClient  # noqa: E402

            self._tenants = AsyncTenantsClient(client_wrapper=self._client_wrapper)
        return self._tenants
