# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.list_environments_response_content import ListEnvironmentsResponseContent
from .raw_client import AsyncRawEnvironmentsClient, RawEnvironmentsClient


class EnvironmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEnvironmentsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListEnvironmentsResponseContent:
        """
        This endpoint provide a list of environments associated with the Team where tenants exist.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEnvironmentsResponseContent
            Environment list retrieved successfully

        Examples
        --------
        from auth0 import Teams

        client = Teams(
            token="YOUR_TOKEN",
        )
        client.environments.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data


class AsyncEnvironmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEnvironmentsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListEnvironmentsResponseContent:
        """
        This endpoint provide a list of environments associated with the Team where tenants exist.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEnvironmentsResponseContent
            Environment list retrieved successfully

        Examples
        --------
        import asyncio

        from auth0 import AsyncTeams

        client = AsyncTeams(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data
